name: Deploy Nextcloud

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push nextcloud image
        uses: docker/build-push-action@v6
        with:
          context: ./nextcloud
          push: true
          tags: ghcr.io/${{ github.repository }}/nextcloud:latest

      - name: Build & push elasticsearch image
        uses: docker/build-push-action@v6
        with:
          context: ./elasticsearch
          push: true
          tags: ghcr.io/${{ github.repository }}/elasticsearch:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add known_hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts

      - name: Rsync project to server
        run: |
          rsync -az --delete \
            --exclude '.git' \
            --exclude '.github' \
            -e "ssh -p ${{ secrets.SSH_PORT }}" \
            ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/srv/nextcloud

      - name: Create/refresh .env on server
        run: |
          ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
          "cd /srv/nextcloud && \
           cp -n .env.sample .env || true && \
           sed -i 's|POSTGRES_PASSWORD=.*|POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}|' .env && \
           sed -i 's|NEXTCLOUD_ADMIN_PASSWORD=.*|NEXTCLOUD_ADMIN_PASSWORD=${{ secrets.NEXTCLOUD_ADMIN_PASSWORD }}|' .env && \
           sed -i 's|NEXTCLOUD_OVERWRITE_HOST=.*|NEXTCLOUD_OVERWRITE_HOST=${{ secrets.NEXTCLOUD_HOST }}|' .env"

      - name: Compose up (prod)
        run: |
          ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
          "cd /srv/nextcloud && \
           docker compose -f docker-compose.yml -f docker-compose.prod.yml pull || true && \
           docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d --build"

      - name: Health checks
        run: |
          ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
          "docker compose -f /srv/nextcloud/docker-compose.yml -f /srv/nextcloud/docker-compose.prod.yml ps && \
           curl -I --max-time 10 http://127.0.0.1:8080/status.php || true && \
           curl -s --max-time 5 http://127.0.0.1:9200 >/dev/null || true"
