name: Deploy to documents.deilmann.sk

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: deploy-prod
  cancel-in-progress: true

  #jbkjlkjlkjl

env:
  HOST: ${{ secrets.SSH_HOST || secrets.VPS_HOST }}
  PORT: ${{ secrets.SSH_PORT || secrets.VPS_PORT || '22' }}
  USER: ${{ secrets.SSH_USER || secrets.VPS_USER || 'deploy' }}
  PATH_REMOTE: ${{ secrets.DEPLOY_PATH || secrets.VPS_PATH || '/opt/nextcloud' }}
  # приватный ключ обязателен в одном из этих секретов:
  KEY: ${{ secrets.SSH_KEY || secrets.VPS_SSH_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check required secrets
        run: |
          test -n "${{ env.HOST }}" || { echo "Missing SSH_HOST (or VPS_HOST)"; exit 1; }
          test -n "${{ env.KEY }}"  || { echo "Missing SSH_KEY (or VPS_SSH_KEY)"; exit 1; }

      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare SSH
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p "${{ env.PORT }}" "${{ env.HOST }}" >> ~/.ssh/known_hosts
          printf "%s" "${{ env.KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Rsync repo to server
        run: |
          rsync -az --delete \
            -e "ssh -i ~/.ssh/id_ed25519 -p ${{ env.PORT }}" \
            --exclude '.git' \
            --exclude '.github' \
            ./  "${{ env.USER }}@${{ env.HOST }}:${{ env.PATH_REMOTE }}/"

      - name: Build & up on server
        run: |
          ssh -i ~/.ssh/id_ed25519 -p "${{ env.PORT }}" \
            "${{ env.USER }}@${{ env.HOST }}" \
            bash -lc '
              set -euo pipefail
              cd "${{ env.PATH_REMOTE }}"
              [ -f .env ] || { echo ".env is missing in $PWD"; exit 1; }
              docker compose pull || true
              docker compose build --pull
              docker compose up -d
              docker image prune -f || true
            '
